# Generated by Django 4.2.11 on 2026-03-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Ruta')),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=15, verbose_name='Estado')),
                ('foto_hoja_ruta', models.ImageField(blank=True, help_text='Sube una foto de la hoja de ruta para extraer los clientes automáticamente con IA.', null=True, upload_to='rutas/fotos/', verbose_name='Foto Hoja de Ruta')),
                ('texto_extraido', models.TextField(blank=True, help_text='Texto detectado automáticamente en la foto.', null=True, verbose_name='Texto extraído OCR')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Ruta del Día',
                'verbose_name_plural': 'Rutas del Día',
                'ordering': ['-fecha'],
                'unique_together': {('fecha', 'conductor')},
            },
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(verbose_name='Orden de visita')),
                ('distancia_anterior_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distancia desde parada anterior (km)')),
                ('hora_estimada', models.TimeField(blank=True, null=True, verbose_name='Hora Estimada')),
                ('hora_real', models.TimeField(blank=True, null=True, verbose_name='Hora Real')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='deliveries.entrega', verbose_name='Entrega')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='routes.rutadia', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Parada de Ruta',
                'verbose_name_plural': 'Paradas de Ruta',
                'ordering': ['ruta', 'orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
    ]
