# Generated by Django 4.2.11 on 2026-03-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_entrega_empresa'),
        ('routes', '0002_rutadia_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradaruta',
            name='entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='deliveries.entrega', verbose_name='Entrega'),
        ),
    ]
