# Generated by Django 4.2.11 on 2026-03-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0006_move_entrega_from_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado_completo', 'Pagado completo'), ('pagado_parcial', 'Pagado parcial'), ('sin_pago', 'Sin pago'), ('credito', 'Credito')], default='pendiente', max_length=20, verbose_name='Estado de pago'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='fecha_registro_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha registro pago'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='pago_registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_pago_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Pago registrado por'),
        ),
        migrations.CreateModel(
            name='EntregaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('credito', 'Credito'), ('transferencia', 'Transferencia')], max_length=15, verbose_name='Metodo de pago')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Monto')),
                ('tiene_documento_credito', models.BooleanField(default=False, help_text='Solo aplica para pagos con metodo credito.', verbose_name='Credito con documento')),
                ('observacion', models.CharField(blank=True, max_length=240, verbose_name='Observacion pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='routes.entrega', verbose_name='Entrega')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_pago_entrega_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Linea de pago de entrega',
                'verbose_name_plural': 'Lineas de pago de entrega',
                'ordering': ['id'],
            },
        ),
    ]
