# Generated by Django 4.2.11 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_entrega_estado_pago_entrega_fecha_registro_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregapago',
            name='metodo',
            field=models.CharField(
                choices=[
                    ('efectivo', 'Efectivo'),
                    ('cheque', 'Cheque'),
                    ('credito', 'Credito'),
                    ('transferencia', 'Transferencia'),
                    ('descuento', 'Descuento'),
                ],
                max_length=15,
                verbose_name='Metodo de pago',
            ),
        ),
    ]
