# Generated by Django 4.2.11 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_entregapago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregapago',
            name='metodo',
            field=models.CharField(
                choices=[
                    ('efectivo', 'Efectivo'),
                    ('cheque', 'Cheque'),
                    ('credito', 'Credito'),
                    ('transferencia', 'Transferencia'),
                    ('descuento', 'Descuento'),
                    ('nula', 'Nula'),
                ],
                max_length=15,
                verbose_name='Metodo de pago',
            ),
        ),
    ]
