# Generated by Django 4.2.11 on 2026-05-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0005_cliente_equivalencia_entregas'),
        ('routes', '0009_alter_entregapago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='comuna_factura_ref',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Comuna factura (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='condicion_pago_ref',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Condición pago (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='dia_factura_ref',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día factura (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='direccion_factura_ref',
            field=models.TextField(blank=True, default='', verbose_name='Dirección factura (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='mes_factura_ref',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes factura (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='numero_factura_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='N° factura (referencia)'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='total_factura_ref',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total factura (referencia)'),
        ),
        migrations.AddField(
            model_name='rutadia',
            name='ocr_facturas_raw',
            field=models.JSONField(blank=True, help_text='Respuesta estructurada del OCR de facturas para revisión.', null=True, verbose_name='OCR facturas (raw)'),
        ),
        migrations.CreateModel(
            name='FacturaOCRLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, default='', max_length=40, verbose_name='N° factura')),
                ('nombre_cliente_ocr', models.CharField(blank=True, default='', max_length=240, verbose_name='Cliente OCR')),
                ('direccion_ocr', models.TextField(blank=True, default='', verbose_name='Dirección OCR')),
                ('comuna_ocr', models.CharField(blank=True, default='', max_length=120, verbose_name='Comuna OCR')),
                ('dia_factura', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Día factura')),
                ('mes_factura', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes factura')),
                ('total_factura', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Total factura')),
                ('transportista', models.CharField(blank=True, default='', max_length=140, verbose_name='Transportista')),
                ('condicion_pago', models.CharField(blank=True, default='', max_length=140, verbose_name='Condición pago')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente validación'), ('confirmada', 'Confirmada'), ('omitida', 'Omitida')], default='pendiente', max_length=12, verbose_name='Estado validación')),
                ('requiere_revision', models.BooleanField(default=False, verbose_name='Requiere revisión')),
                ('observacion_validacion', models.CharField(blank=True, default='', max_length=240, verbose_name='Observación validación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha validación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('audit_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_ocr_validadas', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_ocr_asociadas', to='clients.cliente', verbose_name='Cliente asociado')),
                ('entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_factura_ocr', to='routes.entrega', verbose_name='Entrega asociada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_ocr', to='routes.rutadia', verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'Línea OCR de factura',
                'verbose_name_plural': 'Líneas OCR de factura',
                'ordering': ['ruta', 'id'],
                'indexes': [models.Index(fields=['ruta', 'numero_factura'], name='routes_fact_ruta_id_6aca2f_idx')],
            },
        ),
    ]
