# Generated by Django 4.2.11 on 2026-05-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0010_entrega_comuna_factura_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteOCRAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_normalizada', models.CharField(max_length=255, unique=True, verbose_name='Clave OCR normalizada')),
                ('nombre_ocr', models.CharField(blank=True, default='', max_length=240, verbose_name='Cliente OCR')),
                ('direccion_ocr', models.TextField(blank=True, default='', verbose_name='Dirección OCR')),
                ('comuna_ocr', models.CharField(blank=True, default='', max_length=120, verbose_name='Comuna OCR')),
                ('bloqueado_por_conflicto', models.BooleanField(default=False, help_text='Si se detectaron asociaciones distintas para la misma clave OCR, no se autoselecciona.', verbose_name='Bloqueado por conflicto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('audit_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_ocr_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_ocr', to='clients.cliente', verbose_name='Cliente asociado')),
            ],
            options={
                'verbose_name': 'Alias OCR de cliente',
                'verbose_name_plural': 'Alias OCR de clientes',
                'ordering': ['-fecha_actualizacion'],
                'indexes': [models.Index(fields=['bloqueado_por_conflicto'], name='routes_clie_bloquea_6a8fd4_idx'), models.Index(fields=['cliente'], name='routes_clie_cliente_5b9d5a_idx')],
            },
        ),
    ]
