# Generated by Django 4.2.11 on 2026-06-10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_clienteocralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutadia',
            name='modalidad',
            field=models.CharField(
                choices=[('estandar', 'Estandar'), ('falabella', 'Falabella')],
                db_index=True,
                default='estandar',
                max_length=20,
                verbose_name='Modalidad de ruta',
            ),
        ),
        migrations.AddField(
            model_name='rutadia',
            name='patente',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Patente asociada a la ruta importada.',
                max_length=20,
                verbose_name='Patente',
            ),
        ),
        migrations.CreateModel(
            name='ParadaFalabellaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_original', models.TextField(blank=True, default='', verbose_name='Direccion original')),
                ('localidad_original', models.CharField(blank=True, default='', max_length=140, verbose_name='Localidad original')),
                ('contacto_original', models.CharField(blank=True, default='', max_length=80, verbose_name='Contacto original')),
                ('estado_direccion', models.CharField(choices=[('pendiente_busqueda', 'Pendiente de busqueda'), ('candidatos_disponibles', 'Candidatos disponibles'), ('requiere_llamada_cliente', 'Requiere llamada al cliente'), ('confirmada_manual', 'Confirmada manualmente')], default='pendiente_busqueda', max_length=30, verbose_name='Estado direccion')),
                ('observacion_llamada', models.CharField(blank=True, default='', max_length=240, verbose_name='Observacion llamada')),
                ('coordenada_manual_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud manual')),
                ('coordenada_manual_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud manual')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('parada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='falabella_meta', to='routes.paradaruta', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Parada Falabella (meta)',
                'verbose_name_plural': 'Paradas Falabella (meta)',
            },
        ),
        migrations.CreateModel(
            name='ParadaUbicacionCandidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='nominatim', max_length=40, verbose_name='Proveedor')),
                ('etiqueta', models.CharField(blank=True, default='', max_length=240, verbose_name='Etiqueta')),
                ('direccion_formateada', models.TextField(blank=True, default='', verbose_name='Direccion formateada')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Score')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden sugerencia')),
                ('seleccionada', models.BooleanField(default=False, verbose_name='Seleccionada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_candidatas', to='routes.paradaruta', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Ubicacion candidata de parada',
                'verbose_name_plural': 'Ubicaciones candidatas de parada',
                'ordering': ['parada_id', 'orden', 'id'],
                'indexes': [models.Index(fields=['parada', 'seleccionada'], name='routes_para_parada__2cc137_idx')],
            },
        ),
    ]
