# Generated by Django 4.2.11 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_rutadia_modalidad_patente_and_falabella_meta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clienteocralias',
            new_name='routes_clie_bloquea_9057d5_idx',
            old_name='routes_clie_bloquea_6a8fd4_idx',
        ),
        migrations.RenameIndex(
            model_name='clienteocralias',
            new_name='routes_clie_cliente_b1d123_idx',
            old_name='routes_clie_cliente_5b9d5a_idx',
        ),
        migrations.RenameIndex(
            model_name='paradaubicacioncandidata',
            new_name='routes_para_parada__daf2e6_idx',
            old_name='routes_para_parada__2cc137_idx',
        ),
    ]
