# Generated by Django 4.2.11 on 2026-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_cliente_tiempo_estimado_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='equivalencia_entregas',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad equivalente de entregas para este cliente (ej: 10 para clientes especiales).', verbose_name='Equivalencia de entregas'),
        ),
    ]
