# Generated by Django 4.2.11 on 2026-06-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=10, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('usuario', 'fecha'), name='uq_asistencia_usuario_fecha'),
        ),
    ]
