# Generated by Django 4.2.11 on 2026-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Día pagado'),
        ),
    ]
