# Generated by Django 4.2.11 on 2026-03-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('total_entregas', models.PositiveIntegerField(default=0, verbose_name='Total Entregas')),
                ('entregadas', models.PositiveIntegerField(default=0, verbose_name='Entregadas')),
                ('fallidas', models.PositiveIntegerField(default=0, verbose_name='Fallidas')),
                ('reprogramadas', models.PositiveIntegerField(default=0, verbose_name='Reprogramadas')),
                ('devueltas', models.PositiveIntegerField(default=0, verbose_name='Devueltas')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación del día')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Historial del Día',
                'verbose_name_plural': 'Historial de Días',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_final', models.CharField(max_length=15, verbose_name='Estado Final')),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_historial', to='deliveries.entrega', verbose_name='Entrega')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='history.historialdia', verbose_name='Historial')),
            ],
            options={
                'verbose_name': 'Detalle de Historial',
                'verbose_name_plural': 'Detalles de Historial',
                'unique_together': {('historial', 'entrega')},
            },
        ),
    ]
