# Generated by Django 4.2.11 on 2026-06-28 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public_delivery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(default=public_delivery.models._generate_tracking_code, max_length=20, unique=True, verbose_name='Código de seguimiento')),
                ('vehicle', models.CharField(choices=[('jac_x200', 'JAC X200 (hasta 1.7 ton)'), ('maxus_c35l', 'Maxus C35L (hasta 3.5 ton)')], default='jac_x200', max_length=20, verbose_name='Vehículo')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('picked_up', 'Retirada'), ('in_route', 'En ruta'), ('delivered', 'Entregada'), ('issue', 'Incidencia')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre conductor')),
                ('scheduled_for', models.DateField(blank=True, null=True, verbose_name='Fecha programada')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono cliente')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_publicas', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
            ],
            options={
                'verbose_name': 'Entrega pública',
                'verbose_name_plural': 'Entregas públicas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParadaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveSmallIntegerField(verbose_name='Orden')),
                ('label', models.CharField(max_length=200, verbose_name='Descripción del punto')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('picked_up', 'Retirada'), ('in_route', 'En ruta'), ('delivered', 'Entregada'), ('issue', 'Incidencia')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora entrega')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notas')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='public_delivery.entregapublica', verbose_name='Entrega')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['stop_order'],
                'unique_together': {('entrega', 'stop_order')},
            },
        ),
        migrations.CreateModel(
            name='EventoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=500, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='public_delivery.entregapublica', verbose_name='Entrega')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='public_delivery.paradapublica', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['created_at'],
            },
        ),
    ]
