# Generated by Django 4.2.11 on 2026-03-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_comunas_dia_exclusivo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recomendacioncliente',
            new_name='planner_rec_plan_id_3c85e4_idx',
            old_name='planner_rec_plan_id_b05665_idx',
        ),
        migrations.RenameIndex(
            model_name='recomendacioncliente',
            new_name='planner_rec_plan_id_7429b8_idx',
            old_name='planner_rec_plan_id_99996e_idx',
        ),
        migrations.RemoveField(
            model_name='planificacionsemanal',
            name='distancia_zona_alejada_km',
        ),
    ]
