# Generated by Django 4.2.11 on 2026-03-02 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=50, unique=True, verbose_name='N° Guía')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del paquete')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('fragil', 'Frágil')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En Ruta'), ('entregado', 'Entregado'), ('fallido', 'Intento Fallido'), ('reprogramado', 'Reprogramado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Entrega Real')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='entregas/evidencia/', verbose_name='Foto Evidencia')),
                ('receptor_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Receptor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='clients.cliente', verbose_name='Cliente')),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Conductor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='companies.empresa', verbose_name='Empresa Solicitante')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-fecha_programada', 'cliente'],
            },
        ),
    ]
