# Generated by Django 4.2.11 on 2026-03-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_empresa_email_alter_empresa_telefono'),
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='companies.empresa', verbose_name='Empresa Solicitante'),
        ),
    ]
