# Generated by Django 4.2.11 on 2026-03-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_entrega_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='numero_guia',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='receptor_nombre',
        ),
    ]
